# Font settings
font_family      JetBrainsMono Nerd Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Cursor
cursor_shape     beam
cursor_blink_interval 0.5

# Window layout
window_padding_width 8
hide_window_decorations no

# Background & Opacity
background_opacity 0.95
background_blur    20

window_padding_width 8

# Special wpgtk Color Placeholders
foreground       #8C9B69
background       #0f0504
cursor           #8C9B69

# Black
color0           #0f0504
color8           #929797

# Red
color1           #8C9B69
color9           #8C9B69

# Green
color2           #708B49
color10          #708B49

# Yellow
color3           #798A84
color11          #798A84

# Blue
color4           #656C53
color12          #656C53

# Magenta
color5           #9EA79D
color13          #9EA79D

# Cyan
color6           #3A5C49
color14          #3A5C49

# White
color7           #d1d8d9
color15          #d1d8d9
