# ~/.config/matugen/templates/kitty.conf

foreground #e0e2e8
background #101418
selection_foreground #243240
selection_background #b9c8da

cursor #e0e2e8
cursor_text_color #101418

active_tab_foreground #101418
active_tab_background #9ccbfb
inactive_tab_foreground #e0e2e8
inactive_tab_background #42474e

# The 16 terminal colors
color0 #101418
color8 #42474e

color1 #ffb4ab
color9 #ffb4ab

color2 #9ccbfb
color10 #9ccbfb

color3 #b9c8da
color11 #b9c8da

color4 #d4bee6
color12 #d4bee6

color5 #31628d
color13 #31628d

color6 #cfe5ff
color14 #cfe5ff

color7 #e0e2e8
color15 #e0e2e8