# output=
font=JetBrainsMono Nerd Font Mono:size=24
dpi-aware=auto
prompt=>
icon-theme=Adwaita
icons-enabled=yes
# fields=filename,name,generic
# password-character=*
# match-mode=fzf
show-actions=no
# terminal=kitty -e
width=40
# horizontal-pad=40
# vertical-pad=8
# inner-pad=0
# letter-spacing=0
# layer=overlay


# 3. Force lines to be much taller to house massive wallpaper previews
line-height=80

# 4. Make the window wider to fit widescreen thumbnails alongside text
lines=8

# 5. Enable the massive side-by-side wallpaper preview when searching
# (0.5 means the large preview takes up 50% of the entire launcher window)
image-size-ratio=0.5

[border]
radius=6
width=2
[colors]
# Strips the '#' and appends 'ff' to meet Fuzzel's RRGGBBAA requirement
background=0a0c0fff
text=2B3947ff
match=9fc0c7ff
selection=6f868bff
selection-text=9fc0c7ff
border=2B3947ff

[border]
width=1
radius=10

[dmenu]
mode=text
exit-immediately-if-empty=no

