[main]
font=monospace:size=12
prompt="❯ "
icon-theme=Adwaita
fields=name,generic,comment,exec
terminal=kitty
layer=top
width=30

[colors]
# wpgtk colors with 'ff' added to the end for full transparency/opacity
background=0f050488
text=8C9B69ff
match=708B49ff
selection=929797ff
selection-text=d1d8d9ff
border=8C9B69ff

[border]
width=2
radius=8
