[files]
current_page=1
recent_files=/home/bhava/.config/keepassxc/keepassxc.ini;/home/bhava/.dotfiles/.scripts/sway-run.sh;/home/bhava/.dotfiles/.scripts/theme-changer.sh;/home/bhava/.config/sway/config;/home/bhava/applications.sh;/mnt/670p/SteamLibrary/steamapps/common/SlayTheSpire/sendToDevs/logs/SlayTheSpire.log;/mnt/670p/SteamLibrary/steamapps/common/SlayTheSpire/sendToDevs/troubleshoot.log;
recent_projects=
FILE_NAME_0=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2Fapplications.sh;0;4
FILE_NAME_1=4666;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.config%2Fsway%2Fconfig;0;4
FILE_NAME_2=1681;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.dotfiles%2F.scripts%2Ftheme-changer.sh;0;4
FILE_NAME_3=306;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.dotfiles%2F.scripts%2Fsway-run.sh;0;4

[VTE]
last_dir=/home/bhava

[project]
session_file=
project_file_path=/home/bhava/projects

[geany]
treeview_position=0
msgwindow_position=1153
geometry=0;0;2546;1385;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=-1
position_find_y=-1
position_replace_x=-1
position_replace_y=-1
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
