[files]
current_page=5
recent_files=/home/bhava/.config/wpg/templates/geany_colorschemes_custom.conf.base;/home/bhava/.cache/wal/colors-waybar.css;/home/bhava/.cache/wal/colors.sh;/home/bhava/.cache/wal/colors.css;/home/bhava/.config/wpg/templates/config_waybar_style.css.base;/home/bhava/.config/waybar/style.css;/home/bhava/.dotfiles/.scripts/sway-run.sh;/home/bhava/.config/wpg/templates/config_mako_config.base;/home/bhava/.config/mako/config;/home/bhava/.dotfiles/stow/waybar/.config/waybar/style.css;
recent_projects=
FILE_NAME_0=1243;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.config%2Fsway%2Fconfig;0;4
FILE_NAME_1=886;CSS;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.config%2Fwaybar%2Fstyle.css;0;4
FILE_NAME_2=461;None;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.config%2Fwpg%2Ftemplates%2Fgeany_colorschemes_custom.conf.base;0;4
FILE_NAME_3=414;None;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.config%2Fwpg%2Ftemplates%2Fstow_conky_conkyrc.base;0;4
FILE_NAME_4=1504;Conf;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.conkyrc;0;4
FILE_NAME_5=272;Sh;0;EUTF-8;1;1;0;%2Fhome%2Fbhava%2F.bashrc;0;4

[VTE]
last_dir=/home/bhava

[project]
session_file=
project_file_path=/home/bhava/projects

[geany]
treeview_position=0
msgwindow_position=1272
geometry=0;0;1268;1385;0;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=true
position_find_x=0
position_find_y=0
position_replace_x=0
position_replace_y=0
position_fif_x=0
position_fif_y=0

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;
